### ISSUE TITLE
Installation Progress

### ISSUE THREAD

**Issue by dendisuhubdy** [KZen-networks/JugglingSwap#1]
I tried doing `yarn install` and thrown this error

```
╰─ yarn install                                                                                                                                                                                              ─╯
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[6/11] ⠄ @kzen-networks/thresh-sig
[-/11] ⠄ waiting...
[3/11] ⠄ dlog-verifiable-enc
[-/11] ⠄ waiting...
error /Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/@kzen-networks/thresh-sig: Command failed.
Exit code: 1
Command: npm run build-rust
Arguments:
Directory: /Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/@kzen-networks/thresh-sig
Output:
npm WARN lifecycle The node binary used for scripts is /var/folders/vp/n_ls06695rnd_jn99t8_8lxc0000gn/T/yarn--1597256473295-0.5741766364922438/node but npm is using /Users/dendisuhubdy/.nvm/versions/node/v10.16.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @kzen-networks/thresh-sig@0.4.0 build-rust /Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/@kzen-networks/thresh-sig
> neon build -r

neon info forcing rebuild for new build settings
neon info running cargo
    Blocking waiting for file lock on package cache
    Updating git repository `https://github.com/KZen-networks/gotham-city`
    Updating git repository `https://github.com/KZen-networks/kms-secp256k1.git`
    Updating git repository `https://github.com/KZen-networks/rust-electrumx-client`
    Updating git repository `https://github.com/KZen-networks/multi-party-ecdsa`
    Updating git repository `https://github.com/KZen-networks/multi-party-eddsa`
    Updating git repository `https://github.com/KZen-networks/multi-party-schnorr`
    Updating git repository `https://github.com/KZen-networks/zk-paillier`
    Updating git repository `https://github.com/KZen-networks/serde_dynamodb`
    Updating git repository `https://github.com/KZen-networks/rust-paillier`
    Blocking waiting for file lock on package cache
 Downloading crates ...
  Downloaded core-foundation-sys v0.6.2
  Downloaded ansi_term v0.11.0
  Downloaded futures-cpupool v0.1.8
  Downloaded httparse v1.3.4
  Downloaded error-chain v0.12.1
  Downloaded miniz_oxide v0.3.2
  Downloaded num-integer v0.1.41
  Downloaded parking_lot_core v0.4.0
  Downloaded nodrop v0.1.13
  Downloaded http-body v0.1.0
  Downloaded byte-tools v0.2.0
  Downloaded iovec v0.1.2
  Downloaded arrayvec v0.4.11
  Downloaded proc-macro2 v0.4.30
  Downloaded generic-array v0.9.0
  Downloaded security-framework-sys v0.3.1
  Downloaded scopeguard v0.3.3
  Downloaded stable_deref_trait v1.1.1
  Downloaded serde v0.8.23
  Downloaded memoffset v0.5.1
  Downloaded fnv v1.0.6
  Downloaded digest v0.7.6
  Downloaded lazy_static v0.2.11
  Downloaded block-padding v0.1.4
  Downloaded regex v1.3.1
  Downloaded tokio-fs v0.1.6
  Downloaded strsim v0.8.0
  Downloaded toml v0.4.10
  Downloaded version_check v0.9.1
  Downloaded crypto-mac v0.5.2
  Downloaded tokio-tcp v0.1.3
  Downloaded crossbeam-epoch v0.7.2
  Downloaded unicase v2.5.1
  Downloaded crossbeam-utils v0.6.6
  Downloaded percent-encoding v2.1.0
  Downloaded rustc_version v0.2.3
  Downloaded lock_api v0.1.5
  Downloaded rand_core v0.5.1
  Downloaded bitflags v1.1.0
  Downloaded c2-chacha v0.2.2
  Downloaded mio v0.6.19
  Downloaded spin v0.5.2
  Downloaded scopeguard v1.0.0
  Downloaded reqwest v0.9.20
  Downloaded hashbrown v0.1.8
  Downloaded bindgen v0.47.3
  Downloaded typeable v0.1.2
  Downloaded version_check v0.1.5
  Downloaded untrusted v0.6.2
  Downloaded tokio-current-thread v0.1.6
  Downloaded tokio-threadpool v0.1.15
  Downloaded uuid v0.7.4
  Downloaded want v0.2.0
  Downloaded yaml-rust v0.3.5
  Downloaded cookie_store v0.7.0
  Downloaded walkdir v2.2.9
  Downloaded devise_codegen v0.2.0
  Downloaded core-foundation v0.6.4
  Downloaded yansi v0.5.0
  Downloaded autocfg v0.1.6
  Downloaded config v0.9.3
  Downloaded cfg-if v0.1.9
  Downloaded arrayref v0.3.5
  Downloaded crossbeam-deque v0.7.1
  Downloaded dtoa v0.4.4
  Downloaded env_logger v0.6.2
  Downloaded xml-rs v0.7.0
  Downloaded tokio-buf v0.1.1
  Downloaded tokio-codec v0.1.1
  Downloaded subtle v2.1.1
  Downloaded ryu v1.0.0
  Downloaded synstructure v0.10.2
  Downloaded textwrap v0.11.0
  Downloaded slab v0.4.2
  Downloaded rand_chacha v0.2.1
  Downloaded humantime v1.3.0
  Downloaded failure v0.1.5
  Downloaded itoa v0.4.4
  Downloaded unicode-normalization v0.1.8
  Downloaded serde_json v1.0.40
  Downloaded crossbeam-queue v0.1.2
  Downloaded indexmap v1.2.0
  Downloaded tokio-reactor v0.1.9
  Downloaded traitobject v0.1.0
  Downloaded tokio-executor v0.1.8
  Downloaded url v2.1.0
  Downloaded tokio-timer v0.2.11
  Downloaded smallvec v0.6.10
  Downloaded sha2 v0.7.1
  Downloaded mime_guess v2.0.1
  Downloaded mio-uds v0.6.7
  Downloaded log v0.3.9
  Downloaded unicode-bidi v0.3.4
  Downloaded tokio v0.1.22
  Downloaded time v0.1.42
  Downloaded num_cpus v1.10.1
  Downloaded percent-encoding v1.0.1
  Downloaded parking_lot v0.7.1
  Downloaded quote v0.6.13
  Downloaded quote v1.0.2
  Downloaded rand v0.3.23
  Downloaded peeking_take_while v0.1.2
  Downloaded mime v0.3.14
  Downloaded yaml-rust v0.4.3
  Downloaded pear_codegen v0.1.2
  Downloaded owning_ref v0.4.0
  Downloaded pear v0.1.2
  Downloaded termcolor v1.0.5
  Downloaded num-traits v0.1.43
  Downloaded mime v0.2.6
  Downloaded rayon-core v1.6.0
  Downloaded yansi v0.4.0
  Downloaded try_from v0.3.2
  Downloaded rocket_contrib v0.4.2
  Downloaded regex-syntax v0.6.12
  Downloaded serde_urlencoded v0.5.5
  Downloaded string v0.2.1
  Downloaded safemem v0.3.2
  Downloaded serde_test v0.8.23
  Downloaded sha2 v0.8.0
  Downloaded serde_derive v1.0.101
  Downloaded devise_core v0.2.0
  Downloaded fsevent v0.4.0
  Downloaded hyper-tls v0.3.2
  Downloaded glob v0.2.11
  Downloaded failure_derive v0.1.5
  Downloaded remove_dir_all v0.5.2
  Downloaded time-test v0.2.1
  Downloaded dirs v1.0.5
  Downloaded rustc-demangle v0.1.16
  Downloaded constant_time_eq v0.1.4
  Downloaded cookie v0.11.1
  Downloaded state v0.4.1
  Downloaded serde-hjson v0.8.2
  Downloaded crc32fast v1.2.0
  Downloaded byteorder v1.3.2
  Downloaded aho-corasick v0.7.6
  Downloaded bytes v0.4.12
  Downloaded rand v0.7.1
  Downloaded blake2b_simd v0.5.8
  Downloaded rusoto_core v0.36.0
  Downloaded getrandom v0.1.12
  Downloaded same-file v1.0.5
  Downloaded hyper v0.10.16
  Downloaded hyper v0.12.35
  Downloaded base64 v0.10.1
  Downloaded security-framework v0.3.1
  Downloaded syn v0.15.44
  Downloaded itertools v0.8.0
  Downloaded http v0.1.18
  Downloaded rust-gmp v0.5.0
  Downloaded notify v4.0.13
  Downloaded bech32 v0.7.1
  Downloaded base64 v0.9.3
  Downloaded tokio-sync v0.1.6
  Downloaded proc-macro2 v1.0.3
  Downloaded ucd-util v0.1.5
  Downloaded quick-error v1.2.2
  Downloaded publicsuffix v1.5.3
  Downloaded ppv-lite86 v0.2.5
  Downloaded rust-ini v0.13.0
  Downloaded bit-vec v0.6.1
  Downloaded rocket_http v0.4.2
  Downloaded rustc-serialize v0.3.24
  Downloaded fsevent-sys v2.0.1
  Downloaded nom v4.2.3
  Downloaded num-traits v0.2.8
  Downloaded net2 v0.2.33
  Downloaded rand v0.4.6
  Downloaded native-tls v0.2.3
  Downloaded filetime v0.2.7
  Downloaded memchr v2.2.1
  Downloaded typenum v1.11.2
  Downloaded vec_map v0.8.1
  Downloaded which v2.0.1
  Downloaded unicase v1.4.2
  Downloaded rusoto_credential v0.15.0
  Downloaded bitcoin_hashes v0.7.1
  Downloaded rocksdb v0.10.1
  Downloaded rocket_codegen v0.4.2
  Downloaded tokio-io v0.1.12
  Downloaded unicode-xid v0.1.0
  Downloaded serde v1.0.101
  Downloaded clap v2.33.0
  Downloaded futures v0.1.29
  Downloaded tempfile v3.1.0
  Downloaded rocket v0.4.2
  Downloaded cryptoxide v0.1.2
  Downloaded flate2 v1.0.11
  Downloaded chrono v0.4.9
  Downloaded url v1.7.2
  Downloaded rusoto_dynamodb v0.36.0
  Downloaded backtrace v0.3.37
  Downloaded h2 v0.1.26
  Downloaded idna v0.1.5
  Downloaded clang-sys v0.26.4
  Downloaded linked-hash-map v0.5.2
  Downloaded matches v0.1.8
  Downloaded language-tags v0.2.2
  Downloaded tokio-udp v0.1.5
  Downloaded log v0.4.8
  Downloaded linked-hash-map v0.3.0
  Downloaded jsonwebtoken v6.0.1
  Downloaded syn v1.0.5
  Downloaded rand v0.5.6
  Downloaded rayon v1.2.0
  Downloaded idna v0.2.0
  Downloaded libloading v0.5.2
  Downloaded hmac v0.5.0
  Downloaded cookie v0.12.0
  Downloaded bitcoin v0.20.0
  Downloaded devise v0.2.0
  Downloaded adler32 v1.0.3
  Downloaded cexpr v0.3.5
  Downloaded atty v0.2.13
  Downloaded unicode-width v0.1.6
  Downloaded tokio-uds v0.2.5
  Downloaded try-lock v0.2.2
  Downloaded block-buffer v0.3.3
  Downloaded md5 v0.3.8
  Downloaded libc v0.2.62
  Downloaded backtrace-sys v0.1.31
  Downloaded merkle-sha3 v0.1.0
  Downloaded rust-crypto v0.2.36
  Downloaded encoding_rs v0.8.19
  Downloaded ring v0.14.6
  Downloaded librocksdb-sys v5.18.3
   Compiling libc v0.2.62
   Compiling cfg-if v0.1.9
   Compiling lazy_static v1.4.0
   Compiling semver-parser v0.7.0
   Compiling either v1.5.3
   Compiling arrayvec v0.4.11
   Compiling nodrop v0.1.13
   Compiling byteorder v1.3.2
   Compiling autocfg v0.1.6
   Compiling scopeguard v1.0.0
   Compiling rayon-core v1.6.0
   Compiling rand_core v0.4.2
   Compiling proc-macro2 v1.0.3
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.5
   Compiling serde v1.0.101
   Compiling log v0.4.8
   Compiling typenum v1.11.2
   Compiling version_check v0.1.5
   Compiling itoa v0.4.4
   Compiling memchr v2.2.1
   Compiling ryu v1.0.0
   Compiling smallvec v0.6.10
   Compiling gcc v0.3.55
   Compiling futures v0.1.29
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.44
   Compiling constant_time_eq v0.1.4
   Compiling arrayref v0.3.5
   Compiling byte-tools v0.3.1
   Compiling hex v0.3.2
   Compiling bitflags v1.1.0
   Compiling scopeguard v0.3.3
   Compiling opaque-debug v0.2.3
   Compiling matches v0.1.8
   Compiling slab v0.4.2
   Compiling rustc-serialize v0.3.24
   Compiling keccak v0.1.0
   Compiling zeroize v0.10.1
   Compiling regex-syntax v0.6.12
   Compiling fnv v1.0.6
   Compiling stable_deref_trait v1.1.1
   Compiling percent-encoding v1.0.1
   Compiling httparse v1.3.4
   Compiling getrandom v0.1.12
   Compiling indexmap v1.2.0
   Compiling fake-simd v0.1.2
   Compiling rustc-demangle v0.1.16
   Compiling core-foundation-sys v0.6.2
   Compiling failure_derive v0.1.5
   Compiling ppv-lite86 v0.2.5
   Compiling safemem v0.3.2
   Compiling try-lock v0.2.2
   Compiling yansi v0.4.0
   Compiling remove_dir_all v0.5.2
   Compiling yansi v0.5.0
   Compiling version_check v0.9.1
   Compiling native-tls v0.2.3
   Compiling subtle v1.0.0
   Compiling unicode-width v0.1.6
   Compiling glob v0.2.11
   Compiling vec_map v0.8.1
   Compiling typeable v0.1.2
   Compiling yaml-rust v0.3.5
   Compiling traitobject v0.1.0
   Compiling ansi_term v0.11.0
   Compiling language-tags v0.2.2
   Compiling strsim v0.8.0
   Compiling percent-encoding v2.1.0
   Compiling quick-error v1.2.2
   Compiling ucd-util v0.1.5
   Compiling regex v0.2.11
   Compiling bit-vec v0.6.1
   Compiling state v0.4.1
   Compiling crc32fast v1.2.0
   Compiling adler32 v1.0.3
   Compiling encoding_rs v0.8.19
   Compiling utf8-ranges v1.0.4
   Compiling bindgen v0.47.3
   Compiling same-file v1.0.5
   Compiling termcolor v1.0.5
   Compiling subtle v2.1.1
error: the legacy LLVM-style asm! syntax is no longer supported
   --> /Users/dendisuhubdy/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-2.1.1/src/lib.rs:151:14
    |
151 |     unsafe { asm!("" :: "r"(&input) :: "volatile") }
    |              ----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |              |
    |              help: replace with: `llvm_asm!`
    |
    = note: consider migrating to the new asm! syntax specified in RFC 2873
    = note: alternatively, switch to llvm_asm! to keep your code working as it is

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/dendisuhubdy/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-2.1.1/src/lib.rs:12:34
   |
12 | #![cfg_attr(feature = "nightly", feature(asm))]
   |                                  ^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/dendisuhubdy/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-2.1.1/src/lib.rs:13:34
   |
13 | #![cfg_attr(feature = "nightly", feature(external_doc))]
   |                                  ^^^^^^^^^^^^^^^^^^^^^

   Compiling serde v0.8.23
error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0554`.
error: could not compile `subtle`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/neon-cli/lib/target.js:121:35)
    at step (/Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/neon-cli/lib/target.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kzen-networks/thresh-sig@0.4.0 build-rust: `neon build -r`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @kzen-networks/thresh-sig@0.4.0 build-rust script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by dendisuhubdy** [comment]
tried to do `rustup install 1.38.0` (rustup install 1.38.0-nightly failed)

```
╰─ yarn install                                                                                                                                                                                              ─╯
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[6/11] ⡀ @kzen-networks/thresh-sig
[2/11] ⡀ tiny-secp256k1
[3/11] ⡀ dlog-verifiable-enc
[4/11] ⡀ keccak
error /Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/dlog-verifiable-enc: Command failed.
Exit code: 1
Command: npm run build-rust
Arguments:
Directory: /Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/dlog-verifiable-enc
Output:
npm WARN lifecycle The node binary used for scripts is /var/folders/vp/n_ls06695rnd_jn99t8_8lxc0000gn/T/yarn--1597257474538-0.26594475804559936/node but npm is using /Users/dendisuhubdy/.nvm/versions/node/v10.16.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> dlog-verifiable-enc@0.3.0 build-rust /Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/dlog-verifiable-enc
> neon build -r

neon info forcing rebuild for new build settings
neon info running cargo
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/dendisuhubdy/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.10/Cargo.toml`

Caused by:
  invalid type: sequence, expected a string for key `badges.travis-ci.cargo-features`
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/neon-cli/lib/target.js:121:35)
    at step (/Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/neon-cli/lib/target.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dlog-verifiable-enc@0.3.0 build-rust: `neon build -r`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dlog-verifiable-enc@0.3.0 build-rust script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by oleiba** [comment]
Hi, please try with `rustup override set nightly-2019-07-10`. Let us know.

**Comment by dendisuhubdy** [comment]
build error still persists @oleiba 

```
╰─ yarn install                                                                                                                                                                                              ─╯
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[6/11] ⠂ @kzen-networks/thresh-sig
[2/11] ⠂ tiny-secp256k1
[3/11] ⠂ dlog-verifiable-enc
[4/11] ⠂ keccak
error /Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/dlog-verifiable-enc: Command failed.
Exit code: 1
Command: npm run build-rust
Arguments:
Directory: /Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/dlog-verifiable-enc
Output:
npm WARN lifecycle The node binary used for scripts is /var/folders/vp/n_ls06695rnd_jn99t8_8lxc0000gn/T/yarn--1597283625949-0.3473543721670256/node but npm is using /Users/dendisuhubdy/.nvm/versions/node/v10.16.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> dlog-verifiable-enc@0.3.0 build-rust /Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/dlog-verifiable-enc
> neon build -r

neon info forcing rebuild for new build settings
neon info running cargo
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
error: failed to download `cfg-if v0.1.10`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/dendisuhubdy/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.10/Cargo.toml`

Caused by:
  invalid type: sequence, expected a string for key `badges.travis-ci.cargo-features`
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/neon-cli/lib/target.js:121:35)
    at step (/Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/dendisuhubdy/github/bitwyre/JugglingSwap/node_modules/neon-cli/lib/target.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dlog-verifiable-enc@0.3.0 build-rust: `neon build -r`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dlog-verifiable-enc@0.3.0 build-rust script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by dendisuhubdy** [comment]
@oleiba I think I know why, on the previous build I modified `/Users/dendisuhubdy/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.10/Cargo.toml` and added a key `cargo-features` that was not supposed to be there

I removed it now and the build errors so far doesn't show up.

**Comment by dendisuhubdy** [comment]
```
╰─ yarn install                                                                                                      ─╯
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 794.41s.
```
