### ISSUE TITLE
Running Examples

### ISSUE THREAD

**Issue by dendisuhubdy** [KZen-networks/JugglingSwap#2]
Starting from `server.ts`

```
╰─ ./server.ts run                                                                                  ─╯
/Users/dendisuhubdy/github/bitwyre/JugglingSwap/demo/server.ts:3
import program from 'commander';
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by oleiba** [comment]
Follow the instructions in the README: https://github.com/KZen-networks/JugglingSwap#server.
Specifically, you should run the .js file from the ./dist directory and not the .ts file:
```
$ cd ./dist/demo
$ export DEBUG=server  # see useful logs throughout the demo
$ chmod +x ./server.js
$ ./server.js run
Server listening on port 8001
```

**Comment by dendisuhubdy** [comment]
Could you reopen this?

there isn't a dist folder, screenshot below @oleiba 

<img width="702" alt="Screen Shot 2020-08-13 at 15 30 16" src="https://user-images.githubusercontent.com/4477337/90112356-12d63c00-dd7a-11ea-8816-373e22659cb5.png">

**Comment by oleiba** [comment]
Did you run
```
$ yarn install
$ yarn run build
```
(you can replace `yarn` with `npm`)?

**Comment by dendisuhubdy** [comment]
Yes running `yarn run build` worked! Thank you Oded!
